spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_database
    username: postgres
    password: password
    initialization-mode: always
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: create

